version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: university_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0926
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  fastapi:
    build: .
    container_name: fastapi
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - mongodb
      - redis
    volumes:
      - .:/app

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A celery_app.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - mongodb
    volumes:
      - .:/app

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A celery_app.celery beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
  mongo_data: